name: 'Copyright Headers'
description: 'An action to add copyright/license headers to files.'
inputs:
  path:
    description: 'The path of the file or directory to add a header to.'
    required: true
    default: '.'
  template:
    description: 'The header template to apply to the files.'
    required: true
    default: 'header.tmpl'
runs:
  using: 'node16'
  main: 'index.js'