on: [push]
jobs: 
  add-license-headers:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: node deploy/index.js ../src